''' The identification of the seizure location is loosely based on the electrode mapping on the brain'''



from datetime import time
from datetime import date


patients = {
    
   
    
   '8': {'sex': 'm',
              'age': 55,
              'ictal_clinical_on_time': [time(19, 53, 57),
                                         time(5, 29, 13),
                                         time(18, 59, 42),
                                         time(3, 15, 59),
                                         time(12, 1, 48),
                                         time(12, 1, 48),
                                         time(12, 4, 46),
                                         time(12, 9, 13),
                                         time(12, 12, 30),
                                         time(18, 25, 9), 
                                         time(20, 59, 16),
                                         time(10, 50, 23),
                                         time(10, 51, 56),
                                         time(11, 7, 16),
                                         time(11, 9, 16)
                                       ],
              'post_ictal_time': [time(19, 54, 22),
                                  time(5, 29, 52),
                                  time(19, 0, 23),
                                  time(3, 15, 59),
                                  time(12, 2, 26),
                                  time(12, 5, 52),
                                  time(12, 9, 13),
                                  time(12, 13, 10),
                                  time(18, 27, 40),
                                  time(21, 0, 5),
                                  time(10, 50, 44),
                                  time(10, 52, 42),
                                  time(11, 7, 16),
                                  time(11, 10, 35)
                                 ],
              'ictal_on_time': [time(19, 53, 56),
                                time(5, 29, 13),
                                time(18, 59, 42),
                                time(3, 15, 57),
                                time(12, 1, 48),
                                time(12, 4, 39),
                                time(12, 9, 13),
                                time(12, 12, 37),
                                time(18, 25, 9),
                                time(20, 59, 16),
                                time(10, 50, 24),
                                time(10, 51, 56),
                                time(11, 7, 16),
                                time(11, 9, 15)
                               ],
              'types_of_seizure': ['F - A - NM',
                                   'F - NA - NM',
                                   'F - A - NM',
                                   'F - NA - M',
                                   'F - A - M',
                                   'F - A - M',
                                   'F - A - M',
                                   'F - A - NM',
                                   'F - NA - Mr', 
                                   'G - Mr',
                                   'F - SG - A - M',
                                   'F - SG - NA - M',
                                   'F - NA - M',
                                   'F - NA - M',

                                  ],

              'location': ['rT',
                           'rT',
                           'rT',
                           'rT',
                           'rT',
                           'rT',
                           'rT',
                           'rF',
                           'lPar - Med',
                           'rT - rPost - rF',
                           'rT - rPost -rF',
                           'rT - rPost - rF',
                           'lT - lPar - lOcc',
                           'rT',
                           'rF - rPost - rT'
                          ],
              'propagation': [], 
              'dates_of_seizure': [date(2016, 5, 9),
                                   date(2016, 5, 10),
                                   date(2016, 5, 12),
                                   date(2016, 5, 13),
                                   date(2016, 5, 13),
                                   date(2016, 5, 13),
                                   date(2016, 5, 13),
                                   date(2016, 5, 13),
                                   date(2016, 5, 13),
                                   date(2016, 5, 13),
                                   date(2016, 5, 14),
                                   date(2016, 5, 17),
                                   date(2016, 5, 17),
                                   date(2016, 5, 17),
                                  ]
       },  
    
'13': {'sex': 'm',
              'age': 55,
              'ictal_clinical_on_time': [time(11, 20, 57),
                                         time(18, 29, 48),
                                         time(19, 19, 58),
                                         time(17, 7, 48),
                                         time(19, 26, 38),
                                         time(19, 39, 16),
                                         time(20, 21, 39),
                                         time(4, 3, 17),
                                         time(10, 34, 1),
                                         time(14, 52, 40), 
                                         time(17, 10, 15),
                                         time(19, 1, 0)
                                       ],
              'post_ictal_time': [time(11, 20, 46),
                                  time(18, 30, 14),
                                  time(19, 20, 54),
                                  time(17, 7, 48),
                                  time(19, 27, 39),
                                  time(19, 39, 50),
                                  time(20, 22, 37),
                                  time(4, 3, 50),
                                  time(10, 35, 1),
                                  time(14, 53, 40), 
                                  time(17, 10, 40),
                                  time(19, 2, 0)
                                 ],
              'ictal_on_time': [time(11, 20, 58),
                                time(18, 29, 48),
                                time(19, 19, 54),
                                time(17, 7, 0),
                                time(19, 26, 39),
                                time(19, 38, 50),
                                time(20, 21, 37),
                                time(4, 2, 50),
                                time(10, 34, 1),
                                time(14, 52, 40), 
                                time(17, 10, 15),
                                time(19, 1, 0)
                               ],
              'types_of_seizure': ['F - NA - NM',
                                   'F,SG - A - NM',
                                   'F - SG - A - NM',
                                   'F - SG - A - NM',
                                   'F - SG - A - M',
                                   'F - SG - A - M',
                                   'F - SG - NA - M',
                                   'F - SG - S - M',
                                   'F - SG - A - M',
                                   'F - SG - A - M',
                                   'F - SG - A - M',
                                   'F - SG - NA - M',
                                  ],

              'location': ['rT - rPar - rOcc ',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rC - rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                           'rPar - rOcc',
                          ],
              'propagation': [], 
              'dates_of_seizure': [date(2015, 11, 10),
                                   date(2015, 11, 10),
                                   date(2015, 11, 11),
                                   date(2015, 11, 11),
                                   date(2015, 11, 11),
                                   date(2015, 11, 11),
                                   date(2015, 11, 11),
                                   date(2015, 11, 12),
                                   date(2015, 11, 12),
                                   date(2015, 11, 12),
                                   date(2015, 11, 12),
                                   date(2015, 11, 12),
                                  ]
       },  
    
 '10': {'sex': 'm',
              'age': 55,
              'ictal_clinical_on_time': [time(6, 44, 7),
                                        time(10, 2, 46),
                                        time(12, 4, 6),
                                        time(17, 24, 58),
                                       ],
              'post_ictal_time': [time(6, 46, 29),
                                  time(10, 4, 1),
                                  time(12, 7, 38),
                                  time(17, 25, 12),
                                 ],
              'ictal_on_time': [time(6, 44, 0),
                                time(10, 2, 45),
                                time(12, 4, 16),
                                time(17, 24, 57),
                               ],
              'types_of_seizure': ['F-SG-A-NM',
                                   'F',
                                   'F',
                                   'F',
                                  ],

              'location': [''],
              'propagation': [], 
              'dates_of_seizure': [date(2016, 9, 15),
                                   date(2016, 9, 15),
                                   date(2016, 9, 15),
                                   date(2016, 9, 15),
                                  ]
       },
    
'7': {'sex': 'm',
             'age': 55, 
             'ictal_clinical_on_time': [
                                        time(4, 20, 47),
                                        time(1, 41, 10),
                                        time(2, 19, 29),
                                        time(5, 59, 16),
                                        time(7, 57, 13),
                                        time(9, 3, 10),
                                        time(10, 47, 24),
                                        time(12, 16, 26)
                                      ],
             'post_ictal_time': [
                                 time(4, 22, 42),
                                 time(1, 41, 55),
                                 time(2, 23, 0)
                                ],
             'ictal_on_time': [
                               time(4, 20, 47),
                               time(1, 41, 7),
                               time(2, 19, 28)
                 
                               ],
             'types_of_seizure': [
                                  'F--M',
                                  'F-A-NM',
                                  'F,SG-M'
                                 ],
             'location': [
                                      'FTr,Tr',
                                      'FTr,Tr',
                                      'Fr,FTr,Tr,TPr'
                                     ], 
             'dates_of_seizure': [date(2016, 7, 6),
                                  date(2016, 7, 8),
                                  date(2016, 7, 8)
                                 ]
             },

'5': {'sex': 'f',
             'age': 55, 
             'ictal_clinical_on_time': [time(9, 1, 41),
                                        time(14, 38, 6),
                                        time(3, 41, 57),
                                        time(5, 59, 16),
                                        time(7, 57, 13),
                                        time(9, 3, 10),
                                        time(10, 47, 24),
                                        time(12, 16, 26),
                                      ],
             'post_ictal_time': [time(9, 3, 8),
                                 None,
                                 None,
                                 None,
                                 None,
                                 None,
                                 None,
                                 None
                                ],
             'ictal_on_time': [time(9, 1, 42),
                               time(14, 38, 6),
                               time(3, 41, 52),
                               time(5, 58, 29),
                               time(7, 57, 13),
                               time(9, 3, 10),
                               time(10, 47, 24),
                               time(12, 16, 26)
                              ],
             'types_of_seizure': ['F,SG-NA-M',
                                  'F-NA-NM',
                                  'F,SG-NA-M',
                                  'F,SG-NA-M',
                                  'F,SG-NA-M',
                                  'F,SG-NA-M',
                                  'F,SG-NA-M',
                                  'F,SG-NA-M',
                                 ],

              'location': ['Cl,FCl',
                           'Cl,FCl',
                           'Cl,FCl',
                           'Cl,FCl',
                           'Cl,FCl',
                           'Cl,FCl',
                           'Cl,FCl'], 

             'dates_of_seizure': [date(2016, 8, 23),
                                  date(2016, 8, 24),
                                  date(2016, 8, 25),
                                  date(2016, 8, 25),
                                  date(2016, 8, 25),
                                  date(2016, 8, 25),
                                  date(2016, 8, 25),
                                  date(2016, 8, 28),
                                 ]
             },
                               
    
    
'4': {'sex': 'f',
             'age': 55, 
             'ictal_clinical_on_time': [time(15, 48, 16),
                                       time(18, 34, 13),
                                       time(10, 22, 26)
                                      ],
             'post_ictal_time': [time(15, 49, 10),
                                 time(18, 36, 1),
                                 time(10, 24, 14)
                                ],
             'ictal_on_time': [time(15, 48, 13),
                               time(18, 34, 14),
                               time(10, 22, 27)
                              ],
             'types_of_seizure': ['F,SG-NA-M',
                                  'F,SG-NA-M',
                                  'F,SG-NA-M'
                                 ],

              'location': ['FTr,Tr',
                           'FTr,Tr',
                           'FTr,Tr',
                           ], 

             'dates_of_seizure': [date(2017, 1, 10),
                                  date(2017, 1, 10),
                                  date(2017, 1, 12),
                                 ]
            },

'3': {'sex': 'f',
             'age': 55, 
             'ictal_clinical_on_time': [time(8, 25, 44),
                                       time(16, 42, 53),
                                       time(21, 45, 12)
                                      ],
             'post_ictal_time': [time(8, 26, 27),
                                 time(16, 45, 14),
                                 time(21, 46, 12)
                                ],
             'ictal_on_time': [time(8, 25, 41),
                               time(16, 41, 35),
                               time(21, 43, 55)
                              ],
             'types_of_seizure': ['G-A-M',
                                  'F-NA-M',
                                  'F-A-M'
                                 ],

              'location': ['FTl,Tl-FTr,Tr',
                           'FTl,Tl',
                           'Fl,Tl'
                            ], 

             'lateralization_onset':['RL',
                                     'L',
                                ],
      
             'ECG leads':['Ecg', 'ECG-'],
             'dates_of_seizure': [date(2017, 4, 20),
                                  date(2017, 4, 20),
                                  date(2017, 4, 20),
                                 ]
            },

'2': {'sex': 'f',
             'age': 55, 
             'ictal_clinical_on_time': [time(15, 48, 16),
                                       time(18, 34, 13),
                                       # time(10, 22, 26)
                                      ],
             'post_ictal_time': [time(15, 49, 10),
                                 time(18, 36, 1),
                                 # time(10, 24, 14)
                                ],
             'ictal_on_time': [time(15, 48, 13),
                               time(18, 34, 14),
                               # time(10, 22, 27)
                              ],
             'types_of_seizure': ['FC',
                                  'FC',
                                  'FC'
                                 ],

              'location': ['FTLR',
                                      'FTLR',
                                      'FTLR'
                                      ], 

             'dates_of_seizure': [date(2017, 1, 10),
                                  date(2017, 1, 10),
                                  # date(2017, 1, 12),
                                 ]
            }


}